"""Generate notebooks/05_hyperparameter_tuning.ipynb — fast Optuna tuning."""
import json, pathlib

ROOT    = pathlib.Path(__file__).parent.parent
NB_PATH = ROOT / "notebooks" / "05_hyperparameter_tuning.ipynb"

def md(*lines): return {"cell_type":"markdown","metadata":{},"source":list(lines)}
def code(*lines): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":list(lines)}

cells = [

md(
"# Notebook 05 -- Hyperparameter Tuning with Optuna\n",
"\n",
"## Why Hyperparameter Tuning Matters\n",
"\n",
"In Notebook 04 we ran XGBoost with reasonable defaults. Defaults are a starting point,\n",
"not a ceiling. Hyperparameter tuning systematically searches the parameter space to\n",
"find the configuration that minimizes validation error.\n",
"\n",
"**Why Optuna over GridSearch or RandomSearch?**\n",
"\n",
"| Method | Strategy | Efficiency |\n",
"|---|---|---|\n",
"| **GridSearch** | Exhaustive -- tries every combination | Exponentially slow (NP-hard) |\n",
"| **RandomSearch** | Random sampling -- no learning between trials | Better, but uninformed |\n",
"| **Optuna (TPE)** | Bayesian -- learns which regions are promising | Finds good params 3-5x faster |\n",
"\n",
"Optuna uses **Tree-structured Parzen Estimators (TPE)**: after each trial, it builds\n",
"a probabilistic model of which parameter values tend to produce low loss. Future trials\n",
"sample from the promising regions of parameter space.\n",
"\n",
"**Additional speedup: MedianPruner**  \n",
"If a trial is performing worse than the median of previous trials at an intermediate\n",
"step (e.g., after 50 boosting rounds), Optuna stops it early -- never wastes time\n",
"on clearly bad configurations.\n",
"\n",
"**Input:** `data/processed/X_train.npy`, `y_train.npy`, `X_test.npy`, `y_test.npy`  \n",
"**Output:** `saved_models/best_xgb_model.joblib`, `reports/best_params.json`\n",
),

code(
"# Cell 2: Imports and data load\n",
"import sys, warnings, json, time\n",
"from pathlib import Path\n",
"\n",
"import numpy as np\n",
"import pandas as pd\n",
"import matplotlib.pyplot as plt\n",
"import seaborn as sns\n",
"import joblib\n",
"import optuna\n",
"from optuna.samplers import TPESampler\n",
"from optuna.pruners import MedianPruner\n",
"from xgboost import XGBRegressor\n",
"from sklearn.model_selection import TimeSeriesSplit, cross_val_score\n",
"from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
"\n",
"warnings.filterwarnings('ignore')\n",
"optuna.logging.set_verbosity(optuna.logging.WARNING)  # suppress trial-level noise\n",
"sys.path.insert(0, str(Path.cwd().parent))\n",
"import config\n",
"\n",
"RANDOM_STATE  = config.RANDOM_STATE\n",
"PROCESSED_DIR = Path('..') / config.PROCESSED_DATA_PATH\n",
"MODELS_DIR    = Path('..') / config.SAVED_MODELS_PATH\n",
"REPORTS_DIR   = Path('..') / 'reports'\n",
"FIGURES_DIR   = Path('..') / config.REPORTS_PATH\n",
"REPORTS_DIR.mkdir(parents=True, exist_ok=True)\n",
"\n",
"sns.set_theme(style='darkgrid', palette='muted', font_scale=1.1)\n",
"\n",
"X_train = np.load(PROCESSED_DIR / 'X_train.npy')\n",
"X_test  = np.load(PROCESSED_DIR / 'X_test.npy')\n",
"y_train = np.load(PROCESSED_DIR / 'y_train.npy')\n",
"y_test  = np.load(PROCESSED_DIR / 'y_test.npy')\n",
"\n",
"print(f'X_train: {X_train.shape}  |  X_test: {X_test.shape}')\n",
"print(f'y_train range: [{y_train.min():.3f}, {y_train.max():.3f}]  (log scale)')\n",
),

md(
"## 5.3  TimeSeriesSplit -- Why Not KFold\n",
"\n",
"Standard KFold shuffles data randomly before creating folds. For time-series data this\n",
"causes **temporal leakage** -- fold 3 training data can contain January 28 trips while\n",
"fold 3 validation data contains January 3 trips (the model trains on the future).\n",
"\n",
"**TimeSeriesSplit always trains on past, validates on future:**\n",
"\n",
"```\n",
"Fold 1: Train [Jan 01-06]  |  Validate [Jan 07-12]\n",
"Fold 2: Train [Jan 01-12]  |  Validate [Jan 13-18]\n",
"Fold 3: Train [Jan 01-18]  |  Validate [Jan 19-24]\n",
"Fold 4: Train [Jan 01-22]  |  Validate [Jan 23-27]\n",
"Fold 5: Train [Jan 01-26]  |  Validate [Jan 27-31]\n",
"```\n",
"\n",
"Each validation fold is always in the future relative to its training fold.\n",
"This gives us 5 reliable, non-leaking validation scores to average for each trial.\n",
"\n",
"**Why 5 folds instead of 3?** More folds = more robust estimate of generalization error.\n",
"With 300k rows and 5 folds, each validation set has ~60k trips -- statistically stable.\n",
),

code(
"# Cell 4: Optuna objective function\n",
"# The objective is called once per trial. Optuna passes a 'trial' object with\n",
"# suggest_* methods that propose a parameter value and track the search history.\n",
"\n",
"CV_SPLITS = 5\n",
"tscv = TimeSeriesSplit(n_splits=CV_SPLITS)\n",
"\n",
"def objective(trial):\n",
"    params = {\n",
"        'n_estimators':       trial.suggest_int('n_estimators', 100, 600),\n",
"        'max_depth':          trial.suggest_int('max_depth', 3, 10),\n",
"        'learning_rate':      trial.suggest_float('learning_rate', 0.01, 0.3, log=True),\n",
"        'subsample':          trial.suggest_float('subsample', 0.5, 1.0),\n",
"        'colsample_bytree':   trial.suggest_float('colsample_bytree', 0.4, 1.0),\n",
"        'reg_alpha':          trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),\n",
"        'reg_lambda':         trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),\n",
"        'min_child_weight':   trial.suggest_int('min_child_weight', 1, 50),\n",
"        'gamma':              trial.suggest_float('gamma', 0.0, 5.0),\n",
"        'random_state':       RANDOM_STATE,\n",
"        'tree_method':        'hist',   # fastest CPU training method\n",
"        'n_jobs':             -1,\n",
"        'verbosity':          0,\n",
"    }\n",
"\n",
"    mae_scores = []\n",
"    for fold_idx, (tr_idx, val_idx) in enumerate(tscv.split(X_train)):\n",
"        X_tr, X_val = X_train[tr_idx], X_train[val_idx]\n",
"        y_tr, y_val = y_train[tr_idx], y_train[val_idx]\n",
"\n",
"        model = XGBRegressor(**params)\n",
"        model.fit(X_tr, y_tr,\n",
"                  eval_set=[(X_val, y_val)],\n",
"                  verbose=False)\n",
"\n",
"        y_pred_log = model.predict(X_val)\n",
"        # Evaluate on original seconds scale\n",
"        mae = mean_absolute_error(np.expm1(y_val), np.expm1(y_pred_log))\n",
"        mae_scores.append(mae)\n",
"\n",
"        # Report intermediate value to allow Optuna to prune bad trials\n",
"        trial.report(np.mean(mae_scores), fold_idx)\n",
"        if trial.should_prune():\n",
"            raise optuna.exceptions.TrialPruned()\n",
"\n",
"    return np.mean(mae_scores)\n",
"\n",
"print('Objective function defined.')\n",
"print(f'TimeSeriesSplit: {CV_SPLITS} folds')\n",
"print('Metric: Mean Absolute Error (seconds) on original scale')\n",
),

md(
"## 5.5  Hyperparameter Search Space -- Why These Bounds?\n",
"\n",
"| Parameter | Range | Reasoning |\n",
"|---|---|---|\n",
"| `n_estimators` | 100-600 | Too few = underfit, too many = diminishing returns + slow |\n",
"| `max_depth` | 3-10 | Shallow trees = underfitting, deep trees = overfitting leaf nodes |\n",
"| `learning_rate` | 0.01-0.3 (log scale) | Low LR needs more trees; log scale because we care about 0.01 vs 0.05 more than 0.2 vs 0.25 |\n",
"| `subsample` | 0.5-1.0 | Row sampling per tree -- below 0.5 loses too much signal |\n",
"| `colsample_bytree` | 0.4-1.0 | Feature sampling -- decorrelates trees, prevents feature dominance |\n",
"| `reg_alpha` | 1e-4 to 10 (log) | L1 regularization -- promotes sparsity in feature weights |\n",
"| `reg_lambda` | 1e-4 to 10 (log) | L2 regularization -- prevents large weights |\n",
"| `min_child_weight` | 1-50 | Minimum sum of instance weight in a leaf -- higher = more conservative splits |\n",
"| `gamma` | 0-5 | Minimum loss reduction to make a split -- higher = fewer splits = simpler trees |\n",
"\n",
"**Why `log=True` for learning_rate?** We sample logarithmically because the meaningful\n",
"range is geometric: 0.01, 0.03, 0.1, 0.3. Uniform sampling would waste 90% of trials\n",
"above 0.03 where diminishing returns kick in.\n",
"\n",
"**Why `tree_method='hist'`?** XGBoost's histogram-based training uses approximate split\n",
"finding with binned features. For 300k rows, this is 3-5x faster than exact split finding\n",
"with no meaningful accuracy loss. This is the default in XGBoost 2.x.\n",
),

code(
"# Cell 6: Run Optuna study -- 50 trials with MedianPruner\n",
"# 50 trials is sufficient for Bayesian optimization to converge on this search space.\n",
"# MedianPruner kills trials that perform worse than the median after each fold.\n",
"\n",
"N_TRIALS = 50\n",
"\n",
"study = optuna.create_study(\n",
"    direction='minimize',\n",
"    sampler=TPESampler(seed=RANDOM_STATE),\n",
"    pruner=MedianPruner(n_startup_trials=10, n_warmup_steps=1),\n",
"    study_name='xgb_eta_tuning'\n",
")\n",
"\n",
"print(f'Starting Optuna optimization: {N_TRIALS} trials, {CV_SPLITS}-fold TimeSeriesSplit')\n",
"print('MedianPruner active -- bad trials will be stopped early.')\n",
"print('-' * 60)\n",
"\n",
"t0 = time.time()\n",
"study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)\n",
"elapsed = time.time() - t0\n",
"\n",
"completed = len([t for t in study.trials if t.state.name == 'COMPLETE'])\n",
"pruned    = len([t for t in study.trials if t.state.name == 'PRUNED'])\n",
"\n",
"print(f'\\nDone in {elapsed/60:.1f} min')\n",
"print(f'Completed: {completed}  |  Pruned (early stopped): {pruned}')\n",
"print(f'Best MAE: {study.best_value:.2f}s')\n",
"print(f'Best params: {study.best_params}')\n",
),

md(
"## 5.7  Interpreting Optimization History\n",
"\n",
"The optimization history plot shows MAE on the y-axis against trial number on the x-axis.\n",
"\n",
"**What to look for:**\n",
"- **Rapid drop in first 10-15 trials:** TPE is quickly learning which parameter regions work\n",
"- **Plateau after ~30 trials:** Search has converged -- more trials would give diminishing returns\n",
"- **Scattered high values:** Pruned or bad trials -- the sampler is still exploring\n",
"- **Best value line:** The minimum achieved -- our baseline for the final model\n",
"\n",
"**Parameter importance plot** shows which hyperparameters mattered most.\n",
"If `learning_rate` has 60% importance, that means tuning it from default was the\n",
"biggest single driver of improvement. Parameters with < 5% importance could have\n",
"been left at default without meaningfully affecting the result.\n",
),

code(
"# Cell 8: Optimization history and parameter importance plots\n",
"\n",
"from optuna.visualization.matplotlib import (\n",
"    plot_optimization_history,\n",
"    plot_param_importances,\n",
")\n",
"\n",
"fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n",
"\n",
"# ---- Optimization history ----\n",
"trials_df = study.trials_dataframe()\n",
"completed_df = trials_df[trials_df['state'] == 'COMPLETE'].copy()\n",
"completed_df['best_so_far'] = completed_df['value'].cummin()\n",
"\n",
"axes[0].scatter(completed_df['number'], completed_df['value'],\n",
"                alpha=0.4, color='steelblue', s=20, label='Trial MAE')\n",
"axes[0].plot(completed_df['number'], completed_df['best_so_far'],\n",
"             color='red', lw=2, label='Best so far')\n",
"axes[0].set_title('Optuna Optimization History')\n",
"axes[0].set_xlabel('Trial Number')\n",
"axes[0].set_ylabel('CV MAE (seconds)')\n",
"axes[0].legend()\n",
"\n",
"# ---- Parameter importance ----\n",
"try:\n",
"    importances = optuna.importance.get_param_importances(study)\n",
"    params_sorted = sorted(importances.items(), key=lambda x: x[1], reverse=True)\n",
"    names, vals = zip(*params_sorted)\n",
"    axes[1].barh(list(names)[::-1], [v*100 for v in vals[::-1]], color='coral')\n",
"    axes[1].set_title('Hyperparameter Importance (%)')\n",
"    axes[1].set_xlabel('Importance (%)')\n",
"except Exception as e:\n",
"    axes[1].text(0.5, 0.5, f'Importance unavailable:\\n{e}',\n",
"                 transform=axes[1].transAxes, ha='center')\n",
"\n",
"plt.tight_layout()\n",
"plt.savefig(FIGURES_DIR / '11_optuna_history.png', dpi=120, bbox_inches='tight')\n",
"plt.show()\n",
"print(f'Best CV MAE: {study.best_value:.2f}s  -- achieved at trial {study.best_trial.number}')\n",
),

md(
"## 5.9  Best Parameters -- Decision\n",
"\n",
"We now retrain the final XGBoost model using the best parameters found by Optuna\n",
"on the **full training set** (not cross-validation folds).\n",
"\n",
"**Why retrain on full training set?**\n",
"During cross-validation, each fold used only 80% of training data (the other 20%\n",
"was the validation fold). The final model should train on ALL available training\n",
"data to maximize information. We trust the CV-tuned parameters will generalize.\n",
"\n",
"**Note on overfitting risk:**\n",
"With 50 trials of hyperparameter search, there is a risk of overfitting to the\n",
"validation folds (hyperparameter overfitting). TimeSeriesSplit mitigates this because\n",
"each fold is a different time period -- parameters that work across 5 different time\n",
"windows are genuinely robust, not just lucky.\n",
),

code(
"# Cell 10: Retrain final model with best params, evaluate on held-out test set\n",
"\n",
"best_params = study.best_params\n",
"best_params.update({'random_state': RANDOM_STATE, 'tree_method': 'hist',\n",
"                    'n_jobs': -1, 'verbosity': 0})\n",
"\n",
"print('Retraining with best params on full X_train...')\n",
"t0 = time.time()\n",
"final_model = XGBRegressor(**best_params)\n",
"final_model.fit(X_train, y_train)\n",
"print(f'Training time: {time.time()-t0:.1f}s')\n",
"\n",
"# Evaluate on held-out test set (never seen during tuning)\n",
"y_pred_log = final_model.predict(X_test)\n",
"y_pred     = np.expm1(y_pred_log)\n",
"y_true     = np.expm1(y_test)\n",
"\n",
"mae  = mean_absolute_error(y_true, y_pred)\n",
"rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n",
"r2   = r2_score(y_true, y_pred)\n",
"mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100\n",
"\n",
"print(f'\\nFinal Model (tuned) on holdout test set:')\n",
"print(f'  MAE:  {mae:.2f} seconds')\n",
"print(f'  RMSE: {rmse:.2f} seconds')\n",
"print(f'  MAPE: {mape:.2f}%')\n",
"print(f'  R2:   {r2:.4f}')\n",
"\n",
"# Save\n",
"model_path = MODELS_DIR / config.MODEL_ARTIFACT_NAME\n",
"joblib.dump(final_model, model_path)\n",
"print(f'\\nSaved -> {model_path}')\n",
"\n",
"# Save best params\n",
"params_out = {k: (float(v) if hasattr(v,'item') else v)\n",
"              for k, v in best_params.items()}\n",
"params_out['cv_best_mae']  = float(study.best_value)\n",
"params_out['test_mae']     = float(mae)\n",
"params_out['test_rmse']    = float(rmse)\n",
"params_out['test_r2']      = float(r2)\n",
"(REPORTS_DIR / 'best_params.json').write_text(\n",
"    json.dumps(params_out, indent=2), encoding='utf-8')\n",
"print(f'Saved -> {REPORTS_DIR}/best_params.json')\n",
),

md(
"## 5.11  Notebook 05 Summary\n",
"\n",
"| Step | What | Result |\n",
"|---|---|---|\n",
"| Sampler | Optuna TPE (Bayesian) | Learns promising parameter regions |\n",
"| Pruner | MedianPruner | Stops bad trials early, saves ~30% compute |\n",
"| CV Strategy | TimeSeriesSplit(5) | No temporal leakage in evaluation |\n",
"| Trials | 50 | Sufficient for Bayesian convergence |\n",
"| Output | `best_xgb_model.joblib` | Used by API and Notebook 06 |\n",
"\n",
"---\n",
"\n",
"## Key Interview Questions -- Notebook 05\n",
"\n",
"**Q: Why Optuna over GridSearchCV?**  \n",
"A: GridSearch tries every combination -- 9 parameters with 5 values each = 5^9 = 2M trials.\n",
"Optuna's TPE sampler is Bayesian: it learns which regions of parameter space produce\n",
"low loss and focuses future trials there. Finds a good solution in 50 trials vs millions.\n",
"\n",
"**Q: What is TPE (Tree-structured Parzen Estimators)?**  \n",
"A: After each trial, TPE fits two density estimates: p(x|good) and p(x|bad) where\n",
"good/bad is defined by whether the trial beat the top-N% cutoff. Next trial samples\n",
"from the region that maximizes p(x|good)/p(x|bad). Effectively models 'where do\n",
"good parameters live?' and samples from there.\n",
"\n",
"**Q: What is MedianPruner?**  \n",
"A: After completing each fold in cross-validation, Optuna reports the intermediate\n",
"score. MedianPruner compares it to the median of all completed trials at the same\n",
"step. If the current trial is worse than the median, it prunes (stops) the trial.\n",
"Saves ~20-30% of compute by not finishing clearly inferior configurations.\n",
"\n",
"**Q: Why retrain on the full training set after tuning?**  \n",
"A: During CV, each fold only uses 80% of training data. The final model should use\n",
"all available historical data. We trust the CV-tuned hyperparameters generalize\n",
"because they performed well across 5 different time periods.\n",
"\n",
"**Q: What is hyperparameter overfitting?**  \n",
"A: After 50 trials of CV-based tuning, the best parameters may have exploited\n",
"idiosyncrasies in the validation folds rather than true generalizable patterns.\n",
"TimeSeriesSplit reduces this risk because 5 folds cover 5 different weeks --\n",
"parameters that consistently work across multiple time periods are genuinely robust.\n",
),

]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
        "language_info": {"name":"python","version":"3.10.0"}
    },
    "nbformat": 4, "nbformat_minor": 5,
}
NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=True), encoding="utf-8")
n_md   = sum(1 for c in cells if c["cell_type"]=="markdown")
n_code = sum(1 for c in cells if c["cell_type"]=="code")
print(f"Notebook 05 written: {len(cells)} cells ({n_md} md, {n_code} code)")
print(f"Path: {NB_PATH}")
