"""Generate notebooks/04_model_selection.ipynb with valid JSON."""
import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent
NB_PATH = ROOT / "notebooks" / "04_model_selection.ipynb"

def md(*lines): return {"cell_type":"markdown","metadata":{},"source":list(lines)}
def code(*lines): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":list(lines)}

cells = [

md(
"# Notebook 04 -- Model Selection: Finding the Best Algorithm\n",
"\n",
"## Approach: Principled Model Selection\n",
"\n",
"We never jump straight to XGBoost. We follow a structured progression:\n",
"\n",
"1. **Baseline** -- how good is a naive 'always predict the mean' strategy?\n",
"2. **Linear Regression** -- does linearity fit the data?\n",
"3. **Ridge Regression** -- does regularization improve Linear Regression?\n",
"4. **Random Forest** -- does non-linearity help (bagging)?\n",
"5. **XGBoost** -- does sequential error correction (boosting) help further?\n",
"\n",
"**Each model teaches us something about the data:**\n",
"- If Linear ~ XGBoost: relationship is mostly linear, features are well-engineered\n",
"- If XGBoost >> Linear: strong non-linear interactions exist (e.g. rush hour x zone)\n",
"- If nothing beats Baseline: features carry no signal (go back to EDA)\n",
"\n",
"**Input:** `data/processed/X_train.npy`, `X_test.npy`, `y_train.npy`, `y_test.npy`  \n",
"**Output:** `saved_models/xgb_baseline.joblib`, `reports/model_comparison.csv`\n",
),

code(
"# Cell 2: Load processed data, define evaluation function\n",
"import sys, warnings\n",
"from pathlib import Path\n",
"\n",
"import numpy as np\n",
"import pandas as pd\n",
"import matplotlib.pyplot as plt\n",
"import seaborn as sns\n",
"import joblib\n",
"\n",
"from sklearn.dummy import DummyRegressor\n",
"from sklearn.linear_model import LinearRegression, Ridge\n",
"from sklearn.ensemble import RandomForestRegressor\n",
"from xgboost import XGBRegressor\n",
"from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\n",
"\n",
"warnings.filterwarnings('ignore')\n",
"sys.path.insert(0, str(Path.cwd().parent))\n",
"import config\n",
"\n",
"RANDOM_STATE  = config.RANDOM_STATE\n",
"PROCESSED_DIR = Path('..') / config.PROCESSED_DATA_PATH\n",
"MODELS_DIR    = Path('..') / config.SAVED_MODELS_PATH\n",
"REPORTS_DIR   = Path('..') / 'reports'\n",
"FIGURES_DIR   = Path('..') / config.REPORTS_PATH\n",
"REPORTS_DIR.mkdir(parents=True, exist_ok=True)\n",
"\n",
"sns.set_theme(style='darkgrid', palette='muted', font_scale=1.1)\n",
"\n",
"X_train = np.load(PROCESSED_DIR / 'X_train.npy')\n",
"X_test  = np.load(PROCESSED_DIR / 'X_test.npy')\n",
"y_train = np.load(PROCESSED_DIR / 'y_train.npy')\n",
"y_test  = np.load(PROCESSED_DIR / 'y_test.npy')\n",
"\n",
"print(f'X_train: {X_train.shape}  X_test: {X_test.shape}')\n",
"print(f'y_train: {y_train.shape}  y_test: {y_test.shape}')\n",
"print(f'y_train range: [{y_train.min():.2f}, {y_train.max():.2f}]  (log scale)')\n",
"print(f'y_test  range: [{y_test.min():.2f}, {y_test.max():.2f}]  (log scale)')\n",
"\n",
"# ---- Evaluation function ----\n",
"results = []\n",
"\n",
"def evaluate_model(name, model, X_tr, y_tr, X_te, y_te):\n",
"    \"\"\"\n",
"    Train model, predict on test set, evaluate on original seconds scale.\n",
"    y_tr and y_te are in log scale; we expm1 back before computing metrics.\n",
"    \"\"\"\n",
"    model.fit(X_tr, y_tr)\n",
"    y_pred_log = model.predict(X_te)\n",
"    y_pred = np.expm1(y_pred_log)  # convert back to seconds\n",
"    y_true = np.expm1(y_te)        # convert back to seconds\n",
"\n",
"    # MAE: average error in seconds -- most interpretable for users\n",
"    mae  = mean_absolute_error(y_true, y_pred)\n",
"    # RMSE: penalizes large errors more -- sensitive to outliers\n",
"    rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n",
"    # MAPE: percentage error -- interpretable across different ETA scales\n",
"    mape = np.mean(np.abs((y_true - y_pred) / y_true)) * 100\n",
"    # R2: proportion of variance explained -- 1.0 is perfect, 0.0 = baseline\n",
"    r2   = r2_score(y_true, y_pred)\n",
"\n",
"    print(f'{name:<30} MAE={mae:.1f}s  RMSE={rmse:.1f}s  MAPE={mape:.1f}%  R2={r2:.3f}')\n",
"    return {'model': name, 'MAE': mae, 'RMSE': rmse, 'MAPE': mape, 'R2': r2, 'fitted': model}\n",
),

md(
"## 4.3  Model 1 -- Baseline (DummyRegressor)\n",
"\n",
"Before training any real model, we establish a **naive baseline**.\n",
"\n",
"`DummyRegressor(strategy='mean')` predicts the mean of the training target for\n",
"every single input, completely ignoring all features.\n",
"\n",
"**Why this matters:**\n",
"- This is our **floor** -- any real model must beat this or our features carry no signal\n",
"- If a sophisticated model barely beats DummyRegressor, something is wrong:\n",
"  either the features are uninformative, or there is a preprocessing bug\n",
"- The gap between baseline and our best model quantifies how much value the\n",
"  features and learning algorithm add\n",
"\n",
"**What to expect:** DummyRegressor will have a high MAE because it ignores all context\n",
"(rush hour, zone, operator). Every real model should improve substantially on this.\n",
),

code(
"# Cell 4: Baseline model\n",
"baseline = evaluate_model(\n",
"    'Baseline (Mean)',\n",
"    DummyRegressor(strategy='mean'),\n",
"    X_train, y_train, X_test, y_test\n",
")\n",
"results.append(baseline)\n",
"print(f'\\nBaseline MAE = {baseline[\"MAE\"]:.1f}s means: predicting the mean ETA for every trip')\n",
"print(f'causes an average error of {baseline[\"MAE\"]:.0f} seconds -- this is our floor.')\n",
),

md(
"## 4.5  Model 2 -- Linear Regression\n",
"\n",
"**What it does:** Fits a linear equation: `y = w1*x1 + w2*x2 + ... + wn*xn + b`\n",
"where each weight `w` represents the contribution of that feature.\n",
"\n",
"**Assumptions:**\n",
"1. Linearity -- the target is a linear function of features\n",
"2. Independence -- observations are i.i.d.\n",
"3. Homoscedasticity -- residuals have constant variance\n",
"4. Normality of residuals\n",
"\n",
"**Why it might struggle here:**\n",
"- Rush hour effect is a step change (binary), not a smooth gradient -- hard for linear model\n",
"- Zone effects are categorical replacements -- target encoding makes them numeric but\n",
"  the relationship to ETA may not be linear\n",
"- ETA interactions (rush hour x zone x operator) are captured poorly by linear terms\n",
"\n",
"**Why we still try it:** Fast to train, highly interpretable, reveals if the log-transformed\n",
"target creates a roughly linear relationship with our features.\n",
),

code(
"# Cell 6: Linear Regression\n",
"lr = evaluate_model(\n",
"    'Linear Regression',\n",
"    LinearRegression(),\n",
"    X_train, y_train, X_test, y_test\n",
")\n",
"results.append(lr)\n",
"improvement = (baseline['MAE'] - lr['MAE']) / baseline['MAE'] * 100\n",
"print(f'\\nImprovement over baseline: {improvement:.1f}%')\n",
"print('Good' if improvement > 5 else 'Small -- features may need non-linear modeling')\n",
),

md(
"## 4.7  Model 3 -- Ridge Regression\n",
"\n",
"**What it adds over Linear Regression:** L2 regularization.\n",
"\n",
"**L2 regularization** adds a penalty to the loss function:\n",
"```\n",
"Loss = MSE + alpha * sum(w_i^2)\n",
"```\n",
"\n",
"This forces coefficients toward zero but **not exactly zero** (unlike Lasso/L1).\n",
"\n",
"**When to prefer Ridge over Linear Regression:**\n",
"1. **Multicollinearity** -- correlated features cause unstable, large coefficients in\n",
"   plain Linear Regression. Ridge shrinks them, reducing variance.\n",
"2. **Overfitting** -- Ridge prevents the model from fitting noise in training data.\n",
"\n",
"**In our dataset:** PULocationID and DOLocationID are target-encoded with correlated\n",
"values (adjacent zones have similar ETAs). This mild multicollinearity is exactly\n",
"where Ridge should help over plain Linear Regression.\n",
"\n",
"**Hyperparameter `alpha`:** Higher alpha = stronger regularization = simpler model.\n",
"We use `alpha=1.0` as a sensible default; Optuna will tune this in Notebook 05 if needed.\n",
),

code(
"# Cell 8: Ridge Regression (L2 regularization)\n",
"ridge = evaluate_model(\n",
"    'Ridge Regression',\n",
"    Ridge(alpha=1.0),\n",
"    X_train, y_train, X_test, y_test\n",
")\n",
"results.append(ridge)\n",
"delta = lr['MAE'] - ridge['MAE']\n",
"print(f'\\nRidge vs Linear MAE: {delta:+.1f}s')\n",
"print('Ridge improved on Linear Regression.' if delta > 0\n",
"      else 'Ridge did not improve -- multicollinearity may be minimal here.')\n",
),

md(
"## 4.9  Model 4 -- Random Forest (Bagging)\n",
"\n",
"**What it does:** Builds many decision trees independently, then averages predictions.\n",
"\n",
"**Bagging (Bootstrap Aggregating):**\n",
"1. Create N random subsamples of the training data (with replacement)\n",
"2. Train one decision tree on each subsample\n",
"3. At each split, only consider a random subset of features (`max_features`)\n",
"4. Average all N predictions\n",
"\n",
"**Why better than a single decision tree:**\n",
"- Single tree: high variance (overfits), low bias\n",
"- Forest: averaging reduces variance while keeping low bias\n",
"- Random feature subsets at each split **decorrelate the trees**\n",
"  (if we used all features, all trees would look similar -- no benefit from averaging)\n",
"\n",
"**Why it handles non-linearity:**\n",
"Decision trees split on thresholds -- they naturally capture step changes like\n",
"the rush hour effect without any feature transformation needed.\n",
"\n",
"**Limitations:**\n",
"- Slower to train than XGBoost for same accuracy\n",
"- More memory (stores all N trees)\n",
"- Does not handle missing values natively\n",
"- Cannot extrapolate beyond training range\n",
),

code(
"# Cell 10: Random Forest\n",
"# min_samples_leaf=50 prevents overfitting to tiny leaf nodes.\n",
"# n_jobs=-1 uses all CPU cores for parallel tree training.\n",
"rf = evaluate_model(\n",
"    'Random Forest',\n",
"    RandomForestRegressor(\n",
"        n_estimators=100,\n",
"        max_depth=10,\n",
"        min_samples_leaf=50,\n",
"        n_jobs=-1,\n",
"        random_state=RANDOM_STATE\n",
"    ),\n",
"    X_train, y_train, X_test, y_test\n",
")\n",
"results.append(rf)\n",
"delta_from_lr = lr['MAE'] - rf['MAE']\n",
"print(f'\\nRandom Forest vs Linear Regression MAE: {delta_from_lr:+.1f}s')\n",
"print('Non-linear modeling helps significantly.' if delta_from_lr > 5\n",
"      else 'Limited non-linear gain -- relationship may be mostly linear.')\n",
),

md(
"## 4.11  Model 5 -- XGBoost (Gradient Boosting)\n",
"\n",
"**Boosting vs Bagging:**\n",
"\n",
"| | Bagging (Random Forest) | Boosting (XGBoost) |\n",
"|---|---|---|\n",
"| Tree construction | **Parallel** -- independent trees | **Sequential** -- each tree corrects previous |\n",
"| Training goal | Reduce variance | Reduce both bias and variance |\n",
"| How trees learn | Random subsamples | Residuals of current ensemble |\n",
"| Risk | Underfitting | Overfitting (mitigated by regularization) |\n",
"\n",
"**How XGBoost specifically works:**\n",
"1. Start with a constant prediction (mean of target)\n",
"2. Compute residuals (prediction errors)\n",
"3. Fit a new small tree to the residuals\n",
"4. Add this tree to the ensemble (scaled by `learning_rate`)\n",
"5. Recompute residuals\n",
"6. Repeat for `n_estimators` rounds\n",
"\n",
"Each new tree focuses on the samples the current ensemble got wrong.\n",
"This makes XGBoost especially effective on hard-to-predict samples.\n",
"\n",
"**Why XGBoost usually wins on tabular data:**\n",
"- Built-in L1 (reg_alpha) and L2 (reg_lambda) regularization\n",
"- Handles missing values natively (learns optimal missing direction)\n",
"- Uses second-order gradients (curvature of loss, not just slope) -> faster convergence\n",
"- Subsampling of rows and columns per tree -> prevents overfitting\n",
"- Parallel split-finding despite sequential tree construction\n",
),

code(
"# Cell 12: XGBoost\n",
"# learning_rate=0.1: step size shrinkage. Lower = more robust, needs more trees.\n",
"# subsample=0.8: each tree trains on 80% of data (row sampling).\n",
"# colsample_bytree=0.8: each tree sees 80% of features (column sampling).\n",
"xgb_result = evaluate_model(\n",
"    'XGBoost',\n",
"    XGBRegressor(\n",
"        n_estimators=300,\n",
"        max_depth=6,\n",
"        learning_rate=0.1,\n",
"        subsample=0.8,\n",
"        colsample_bytree=0.8,\n",
"        random_state=RANDOM_STATE,\n",
"        n_jobs=-1,\n",
"        verbosity=0\n",
"    ),\n",
"    X_train, y_train, X_test, y_test\n",
")\n",
"results.append(xgb_result)\n",
"delta_from_rf = rf['MAE'] - xgb_result['MAE']\n",
"print(f'\\nXGBoost vs Random Forest MAE: {delta_from_rf:+.1f}s')\n",
"print('Boosting outperforms bagging here.' if delta_from_rf > 0\n",
"      else 'Minimal difference -- both ensemble methods comparable on this dataset.')\n",
),

md(
"## 4.13  Model Comparison -- What the Numbers Tell Us\n",
"\n",
"We now compare all 5 models on the same holdout test set.\n",
"\n",
"**Reading the comparison table:**\n",
"- **MAE (seconds):** Average absolute error. Most interpretable: 'on average, off by X seconds'\n",
"- **RMSE:** Squares errors before averaging -- more sensitive to large errors\n",
"- **MAPE (%):** Percentage error -- interpretable regardless of ETA scale\n",
"- **R2:** Proportion of variance explained. 0.0 = same as baseline, 1.0 = perfect\n",
"\n",
"We sort by **MAE** as our primary metric because:\n",
"- MAE treats all errors equally -- a 60-second error counts as 60 seconds\n",
"- RMSE would inflate the penalty for a few very long ETAs (traffic incidents)\n",
"  making it unrepresentative of typical user experience\n",
"- From a product perspective, MAE directly translates to 'average user impact'\n",
),

code(
"# Cell 14: Build comparison table and bar chart\n",
"\n",
"# Build comparison DataFrame (exclude 'fitted' key)\n",
"compare_df = pd.DataFrame([\n",
"    {k: v for k, v in r.items() if k != 'fitted'}\n",
"    for r in results\n",
"]).sort_values('MAE').reset_index(drop=True)\n",
"\n",
"print('=== Model Comparison (sorted by MAE) ===')\n",
"display(compare_df.round(2))\n",
"\n",
"# Bar chart\n",
"fig, ax = plt.subplots(figsize=(10, 6))\n",
"colors = ['#FF6B6B' if m == 'Baseline (Mean)' else '#4ECDC4' for m in compare_df['model']]\n",
"bars = ax.barh(compare_df['model'], compare_df['MAE'], color=colors)\n",
"\n",
"# Add value labels on bars\n",
"for bar, val in zip(bars, compare_df['MAE']):\n",
"    ax.text(bar.get_width() + 0.3, bar.get_y() + bar.get_height()/2,\n",
"            f'{val:.1f}s', va='center', fontsize=10)\n",
"\n",
"baseline_mae = results[0]['MAE']  # first result is always baseline\n",
"ax.axvline(baseline_mae, color='red', ls='--', lw=1.5, label=f'Baseline: {baseline_mae:.1f}s')\n",
"ax.set_xlabel('MAE (seconds) -- lower is better')\n",
"ax.set_title('Model Comparison -- MAE on Holdout Test Set')\n",
"ax.legend()\n",
"plt.tight_layout()\n",
"plt.savefig(FIGURES_DIR / '10_model_comparison.png', dpi=120, bbox_inches='tight')\n",
"plt.show()\n",
),

md(
"## 4.15  Decision: Why We Proceed With XGBoost\n",
"\n",
"Based on the comparison above, XGBoost achieves the lowest MAE on the holdout test set.\n",
"\n",
"**Interpreting the gap between Linear Regression and XGBoost:**\n",
"- **Large gap (> 10s):** Strong non-linear interactions exist in the data.\n",
"  The model benefits significantly from non-linear splits. This is expected given\n",
"  that rush hour effects, zone-specific patterns, and operator differences all\n",
"  interact in complex ways.\n",
"- **Small gap (< 5s):** Relationship is mostly linear -- features are well-engineered\n",
"  and log-transform captured most non-linearity.\n",
"\n",
"**Why XGBoost over Random Forest if they perform similarly?**\n",
"- XGBoost trains faster for the same number of estimators\n",
"- Uses less memory in production (leaf-level rather than node-level parallelism)\n",
"- Built-in regularization (reg_alpha, reg_lambda) is more flexible\n",
"- Better supported in production systems (ONNX, Triton Inference Server)\n",
"- Hyperparameter tuning with Optuna is more effective for gradient boosting\n",
"\n",
"**Next steps:** Notebook 05 will use Optuna to tune XGBoost hyperparameters with\n",
"100 trials and TimeSeriesSplit cross-validation.\n",
),

md(
"## 4.16  A Note on Cross-Validation\n",
"\n",
"In this notebook we used a **simple chronological train/test split** for speed.\n",
"Each model was trained once on 80% of data and evaluated on 20%.\n",
"\n",
"**Limitation:** A single split is noisy -- the test set might happen to be an\n",
"unusually easy or hard period. One bad week in January could skew all metrics.\n",
"\n",
"**In Notebook 05 (hyperparameter tuning)** we will use:\n",
"```\n",
"TimeSeriesSplit(n_splits=5)\n",
"```\n",
"\n",
"**Why TimeSeriesSplit and NOT standard KFold?**\n",
"\n",
"KFold randomly shuffles the data before creating folds. This means:\n",
"- Fold 3 training set: trips from Jan 28, Jan 5, Jan 17 (shuffled)\n",
"- Fold 3 validation set: trips from Jan 2, Jan 25, Jan 8\n",
"\n",
"The model trains on January 28th data to predict January 2nd data.\n",
"This is temporal leakage -- the model sees the 'future' during training.\n",
"\n",
"TimeSeriesSplit guarantees:\n",
"- **Fold 1:** Train on Jan 1-6, validate on Jan 7-12\n",
"- **Fold 2:** Train on Jan 1-12, validate on Jan 13-18\n",
"- **Fold 3:** Train on Jan 1-18, validate on Jan 19-24\n",
"- etc.\n",
"\n",
"Always trains on past, validates on future -- exactly like production.\n",
),

md(
"## 4.17  Key Interview Questions -- Notebook 04\n",
"\n",
"**Q: Why do you always start with a baseline model?**  \n",
"A: The baseline establishes the minimum performance any model must exceed. If your\n",
"complex model barely beats 'always predict the mean', either the features carry no\n",
"signal or there is a bug. The baseline also gives a meaningful scale to improvements:\n",
"'XGBoost reduced error by 40% vs baseline' is far more informative than 'MAE = 85s'.\n",
"\n",
"**Q: What is the difference between bagging and boosting?**  \n",
"A: Bagging (Random Forest) builds trees in PARALLEL on random subsamples and averages\n",
"predictions -- reduces variance. Boosting (XGBoost) builds trees SEQUENTIALLY, each\n",
"correcting the errors of the previous -- reduces both bias and variance but risks\n",
"overfitting (mitigated by regularization and subsampling).\n",
"\n",
"**Q: Why does XGBoost usually beat Random Forest on tabular data?**  \n",
"A: Sequential error correction focuses effort on hard samples. Second-order gradient\n",
"optimization converges faster. Built-in L1/L2 regularization. Native missing value\n",
"handling. Row and column subsampling per tree prevents overfitting. In practice,\n",
"XGBoost consistently outperforms Random Forest on structured/tabular datasets.\n",
"\n",
"**Q: What is regularization and when do you use Ridge over Linear?**  \n",
"A: Regularization adds a penalty on large coefficients to the loss function, preventing\n",
"overfitting. Ridge (L2) shrinks all coefficients toward zero without eliminating any.\n",
"Use Ridge over Linear when: features are correlated (multicollinearity), when the\n",
"model overfits (gap between train and test score), or when you have more features\n",
"than samples.\n",
"\n",
"**Q: Why MAE over RMSE as the primary metric?**  \n",
"A: RMSE squares errors before averaging -- a few very long ETAs caused by traffic\n",
"incidents would disproportionately inflate RMSE and make it unrepresentative of\n",
"typical user experience. MAE gives equal weight to all errors, directly translating\n",
"to 'average user impact in seconds'. For operational decisions, MAE is more honest.\n",
"\n",
"**Q: Why TimeSeriesSplit instead of KFold?**  \n",
"A: KFold randomly shuffles data, allowing the model to train on 'future' trips to\n",
"predict 'past' trips -- temporal leakage. TimeSeriesSplit always trains on chronologically\n",
"earlier data and validates on later data, exactly simulating production conditions.\n",
"\n",
"**Q: What does R2 mean and what is a good value?**  \n",
"A: R2 (coefficient of determination) = 1 - (SS_residual / SS_total). It measures the\n",
"proportion of target variance explained by the model. 0.0 = same as predicting the mean.\n",
"1.0 = perfect predictions. For taxi ETA prediction, R2 of 0.5-0.7 is realistic given\n",
"inherent randomness in traffic conditions. Higher R2 often indicates data leakage.\n",
),

code(
"# Cell 18: Save best model and results\n",
"\n",
"# Save the fitted XGBoost model\n",
"xgb_model_path = MODELS_DIR / 'xgb_baseline.joblib'\n",
"joblib.dump(xgb_result['fitted'], xgb_model_path)\n",
"print(f'XGBoost model saved -> {xgb_model_path}')\n",
"\n",
"# Save comparison table\n",
"results_csv = REPORTS_DIR / 'model_comparison.csv'\n",
"compare_df.to_csv(results_csv, index=False)\n",
"print(f'Results table saved -> {results_csv}')\n",
"\n",
"print()\n",
"print('=== Final Summary ===')\n",
"best = compare_df.iloc[0]\n",
"print(f'Best model: {best[\"model\"]}')\n",
"print(f'  MAE:  {best[\"MAE\"]:.1f}s')\n",
"print(f'  RMSE: {best[\"RMSE\"]:.1f}s')\n",
"print(f'  MAPE: {best[\"MAPE\"]:.1f}%')\n",
"print(f'  R2:   {best[\"R2\"]:.3f}')\n",
"print()\n",
"print('Notebooks 03 and 04 complete.')\n",
"print('Next: Notebook 05 -- Hyperparameter tuning with Optuna and TimeSeriesSplit CV.')\n",
),

]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=True), encoding="utf-8")
n_md   = sum(1 for c in cells if c["cell_type"] == "markdown")
n_code = sum(1 for c in cells if c["cell_type"] == "code")
print(f"Notebook 04 written: {len(cells)} cells ({n_md} markdown, {n_code} code)")
print(f"Path: {NB_PATH}")
