"""Generate notebooks/03_feature_engineering.ipynb with valid JSON."""
import json, pathlib

ROOT = pathlib.Path(__file__).parent.parent
NB_PATH = ROOT / "notebooks" / "03_feature_engineering.ipynb"

def md(*lines): return {"cell_type":"markdown","metadata":{},"source":list(lines)}
def code(*lines): return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":list(lines)}

cells = [

md(
"# Notebook 03 -- Feature Engineering: Building the Feature Pipeline\n",
"\n",
"## Goal\n",
"\n",
"Transform raw, messy trip data into a clean feature matrix that a model can learn from.\n",
"\n",
"## The Golden Rule of Feature Engineering\n",
"\n",
"> **ALL transformations must be learned on training data only and applied to test data.**\n",
"> Never fit transformers on the full dataset before splitting.\n",
"\n",
"Why? If we compute mean ETA per zone on the full dataset, then split into train/test,\n",
"the test set's zone statistics have already influenced the encoding. The model has\n",
"'seen' the test set before evaluation -- this is preprocessing leakage.\n",
"\n",
"**Solution:** `sklearn.pipeline.Pipeline` + `ColumnTransformer` enforce this rule\n",
"automatically. We `.fit()` only on `X_train`, then `.transform()` both `X_train`\n",
"and `X_test`. The test set is never touched during fitting.\n",
"\n",
"**Input:** `data/interim/sample_filtered.parquet`  \n",
"**Output:**\n",
"- `data/processed/X_train.npy`, `X_test.npy`, `y_train.npy`, `y_test.npy`\n",
"- `saved_models/preprocessor.joblib`\n",
),

code(
"# Cell 2: Imports and data load\n",
"import sys, warnings\n",
"from pathlib import Path\n",
"\n",
"import numpy as np\n",
"import pandas as pd\n",
"import matplotlib.pyplot as plt\n",
"import seaborn as sns\n",
"import joblib\n",
"\n",
"from sklearn.pipeline import Pipeline\n",
"from sklearn.compose import ColumnTransformer\n",
"from sklearn.preprocessing import StandardScaler\n",
"\n",
"warnings.filterwarnings('ignore')\n",
"sys.path.insert(0, str(Path.cwd().parent))\n",
"import config\n",
"\n",
"RANDOM_STATE  = config.RANDOM_STATE\n",
"INTERIM_DIR   = Path('..') / config.INTERIM_DATA_PATH\n",
"PROCESSED_DIR = Path('..') / config.PROCESSED_DATA_PATH\n",
"MODELS_DIR    = Path('..') / config.SAVED_MODELS_PATH\n",
"PROCESSED_DIR.mkdir(parents=True, exist_ok=True)\n",
"MODELS_DIR.mkdir(parents=True, exist_ok=True)\n",
"\n",
"df = pd.read_parquet(INTERIM_DIR / config.INTERIM_FILTERED_NAME)\n",
"\n",
"for col in ['request_datetime','on_scene_datetime']:\n",
"    if col in df.columns and df[col].dtype == object:\n",
"        df[col] = pd.to_datetime(df[col], errors='coerce')\n",
"\n",
"print(f'Loaded: {df.shape[0]:,} rows x {df.shape[1]} cols')\n",
"print(f'\\nDtypes:')\n",
"print(df.dtypes.to_string())\n",
),

md(
"## 3.3  Data Leakage Column Audit\n",
"\n",
"Before building any features, we must classify every column as SAFE or LEAKY.\n",
"Using a leaky column gives artificially perfect offline results but the model\n",
"fails completely in production because those values do not exist at prediction time.\n",
"\n",
"**This is the most common mistake junior data scientists make.**\n",
"\n",
"### SAFE TO USE (known at the moment the rider submits the request)\n",
"\n",
"| Column | Reasoning |\n",
"|---|---|\n",
"| `request_datetime` | The exact moment the rider tapped 'Request' -- our time-zero |\n",
"| `PULocationID` | Rider's current GPS location maps to a TLC zone -- known immediately |\n",
"| `DOLocationID` | Rider entered their destination in the app |\n",
"| `hvfhs_license_num` | Identifies the app (Uber vs Lyft) -- known from session context |\n",
"| `shared_request_flag` | Rider chose 'shared ride' option before requesting |\n",
"| `wav_request_flag` | Rider specified wheelchair accessible vehicle |\n",
"\n",
"### LEAKY -- known only AFTER the trip starts or ends\n",
"\n",
"| Column | Why it leaks |\n",
"|---|---|\n",
"| `trip_miles` | GPS tracks this DURING the trip -- not available at request time |\n",
"| `trip_time` | Total trip duration -- only known when rider exits vehicle |\n",
"| `base_passenger_fare` | Calculated after trip completes |\n",
"| `driver_pay` | Paid after trip completes |\n",
"| `tips` | Given after trip ends |\n",
"| `tolls` | Incurred during the trip |\n",
"| `pickup_datetime` | This is AFTER the driver arrived -- leaks our own target |\n",
"| `dropoff_datetime` | End of trip -- pure future information |\n",
"| `on_scene_datetime` | This IS our target's source -- cannot also be a feature |\n",
"\n",
"**Using any leaky column would make the model look perfect in evaluation\n",
"but produce garbage predictions in production where none of these values exist yet.**\n",
),

md(
"## 3.4  Feature Engineering Rationale\n",
"\n",
"Here is every feature we will build, and the business/statistical reason for each:\n",
"\n",
"**`pickup_hour`** (0-23)  \n",
"Driver availability and traffic patterns vary dramatically by hour. Rush hour means\n",
"more congestion and more demand -- longer ETA. 3am has less traffic but fewer drivers.\n",
"Hour captures complex non-linear temporal patterns that a tree model can learn.\n",
"\n",
"**`pickup_day_of_week`** (0-6, Mon=0)  \n",
"Monday morning vs Saturday night have completely different supply-demand dynamics.\n",
"Used both as numeric and to derive the binary flags below.\n",
"\n",
"**`is_weekend`** (0/1)  \n",
"Binary simplification of `pickup_day_of_week`. Our Mann-Whitney test in Notebook 02\n",
"confirmed a statistically significant ETA difference between weekdays and weekends.\n",
"\n",
"**`is_rush_hour`** (0/1)  \n",
"7-9am and 5-7pm -- peak congestion windows. Binary flag lets the model learn a step-change\n",
"in ETA (rush vs not-rush) rather than a smooth gradient over hours.\n",
"\n",
"**`is_night`** (0/1)  \n",
"10pm-5am. Late night has less traffic but also fewer available drivers -- complex trade-off\n",
"that a binary flag can help the model learn.\n",
"\n",
"**`PULocationID` -> Target Encoded**  \n",
"Pickup zone is one of the strongest predictors. Manhattan Midtown vs Queens residential\n",
"areas have fundamentally different driver supply. With ~265 unique zones, one-hot encoding\n",
"creates 265 sparse binary columns causing dimensionality and multicollinearity problems.\n",
"Target encoding replaces each zone with its smoothed mean ETA -- a single informative\n",
"numeric column. Industry standard for high-cardinality categoricals.\n",
"\n",
"**`DOLocationID` -> Target Encoded**  \n",
"Destination affects which drivers accept the trip. A driver near JFK may decline a\n",
"Queens pickup if the destination is the Bronx (bad repositioning). Same target encoding.\n",
"\n",
"**`operator`** (0=Uber, 1=Lyft)  \n",
"Our Mann-Whitney test showed statistically significant ETA differences between operators.\n",
"Label-encoded since there are only 2 values.\n",
"\n",
"**`shared_request_flag`** (0/1)  \n",
"Pooled rides may attract different driver behavior -- drivers may route to pick up\n",
"a second rider, affecting the first rider's ETA.\n",
"\n",
"**`wav_request_flag`** (0/1)  \n",
"Wheelchair accessible vehicles are rarer in the fleet -- longer ETA expected.\n",
),

code(
"# Cell 5: Build time and categorical features from request_datetime\n",
"\n",
"# ---- Time features ----\n",
"df['pickup_hour']        = df['request_datetime'].dt.hour\n",
"df['pickup_day_of_week'] = df['request_datetime'].dt.dayofweek  # 0=Monday, 6=Sunday\n",
"df['is_weekend']         = (df['pickup_day_of_week'] >= 5).astype(int)\n",
"df['is_rush_hour']       = df['pickup_hour'].isin([7,8,9,17,18,19]).astype(int)\n",
"df['is_night']           = df['pickup_hour'].isin([22,23,0,1,2,3,4]).astype(int)\n",
"\n",
"# ---- Operator encoding ----\n",
"# HV0003=Uber->0, HV0005=Lyft->1, unknown->-1\n",
"df['operator'] = df['hvfhs_license_num'].map({'HV0003': 0, 'HV0005': 1}).fillna(-1).astype(int)\n",
"\n",
"# ---- Flag encoding ----\n",
"for flag_col in ['shared_request_flag', 'wav_request_flag']:\n",
"    if flag_col in df.columns:\n",
"        df[flag_col] = (df[flag_col] == 'Y').astype(int)\n",
"    else:\n",
"        df[flag_col] = 0  # column absent in some versions of the dataset\n",
"\n",
"# ---- Verification ----\n",
"new_features = ['pickup_hour','pickup_day_of_week','is_weekend',\n",
"                'is_rush_hour','is_night','operator',\n",
"                'shared_request_flag','wav_request_flag']\n",
"print('Feature value distributions:')\n",
"for col in new_features:\n",
"    vc = df[col].value_counts().sort_index()\n",
"    print(f'  {col:<25}: {dict(vc)}')\n",
),

md(
"## 3.6  Target Variable Decision -- Should We Log-Transform?\n",
"\n",
"In Notebook 02 we saw that `eta_seconds` is right-skewed. We now choose whether to\n",
"train on the raw target or a transformed version.\n",
"\n",
"**Option A: Train on `eta_seconds` directly**  \n",
"- Model minimizes RMSE on raw scale\n",
"- Large ETAs (rare long pickups) dominate the loss function\n",
"- Model may underfit short ETAs (the majority) to better predict rare long ones\n",
"\n",
"**Option B: Train on `log1p(eta_seconds)` (log-transform)**  \n",
"- Model trains on a more symmetric, bell-shaped distribution\n",
"- All ETA ranges have more balanced influence on the loss\n",
"- Residuals are closer to normally distributed (satisfies linear model assumptions)\n",
"- After prediction: `predicted_eta = np.expm1(model.predict(X))`\n",
"- This is the approach used in production at Uber/Lyft for skewed regression targets\n",
"\n",
"**Decision: We train on `log1p(eta_seconds)` and evaluate on original seconds scale.**\n",
"\n",
"This is a principled, widely-used production technique for right-skewed regression targets.\n",
),

code(
"# Cell 7: Create log-transformed target, compare distributions\n",
"import matplotlib.pyplot as plt\n",
"import seaborn as sns\n",
"sns.set_theme(style='darkgrid', font_scale=1.1)\n",
"\n",
"df['log_eta'] = np.log1p(df['eta_seconds'])\n",
"\n",
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n",
"\n",
"sns.histplot(df['eta_seconds'], bins=60, kde=True, ax=axes[0], color='steelblue')\n",
"axes[0].set_title('Target: eta_seconds (Raw)')\n",
"axes[0].set_xlabel('ETA (seconds)')\n",
"\n",
"sns.histplot(df['log_eta'], bins=60, kde=True, ax=axes[1], color='coral')\n",
"axes[1].set_title('Target: log1p(eta_seconds)')\n",
"axes[1].set_xlabel('log1p(ETA seconds)')\n",
"\n",
"plt.suptitle('Raw vs Log-Transformed Target', fontsize=13)\n",
"plt.tight_layout()\n",
"plt.savefig(Path('..') / config.REPORTS_PATH / '09_log_target.png',\n",
"            dpi=120, bbox_inches='tight')\n",
"plt.show()\n",
"\n",
"print(f'Skewness before log: {df[\"eta_seconds\"].skew():.3f}')\n",
"print(f'Skewness after  log: {df[\"log_eta\"].skew():.3f}')\n",
"print('log1p significantly reduces skewness -- confirms our target transform decision.')\n",
),

md(
"## 3.8  Train-Test Split Strategy -- Why Chronological, Not Random\n",
"\n",
"**The wrong approach: random split**\n",
"\n",
"If we randomly split the dataset, training data will contain trips from January 25th\n",
"and test data will contain trips from January 3rd. The model trains on 'future' data\n",
"to predict 'past' data.\n",
"\n",
"This is **temporal data leakage** -- offline metrics look great, production fails.\n",
"\n",
"**The right approach: chronological split**\n",
"\n",
"Sort by `request_datetime`, use:\n",
"- **First 80%** of trips as training data (January 1 - January 25 approximately)\n",
"- **Last 20%** of trips as test data (January 25 - January 31 approximately)\n",
"\n",
"This simulates real production: **train on historical data, predict on future data**.\n",
"\n",
"The date ranges must not overlap. We will verify this explicitly.\n",
),

code(
"# Cell 9: Chronological train-test split 80/20\n",
"\n",
"FEATURES = [\n",
"    'pickup_hour', 'pickup_day_of_week', 'is_weekend',\n",
"    'is_rush_hour', 'is_night', 'PULocationID',\n",
"    'DOLocationID', 'operator', 'shared_request_flag',\n",
"    'wav_request_flag'\n",
"]\n",
"TARGET = 'log_eta'\n",
"\n",
"# Sort chronologically before splitting\n",
"df_sorted = df.sort_values('request_datetime').reset_index(drop=True)\n",
"\n",
"split_idx = int(len(df_sorted) * 0.80)\n",
"\n",
"X_train = df_sorted[FEATURES].iloc[:split_idx].copy()\n",
"X_test  = df_sorted[FEATURES].iloc[split_idx:].copy()\n",
"y_train = df_sorted[TARGET].iloc[:split_idx].copy()\n",
"y_test  = df_sorted[TARGET].iloc[split_idx:].copy()\n",
"\n",
"train_start = df_sorted['request_datetime'].iloc[0]\n",
"train_end   = df_sorted['request_datetime'].iloc[split_idx - 1]\n",
"test_start  = df_sorted['request_datetime'].iloc[split_idx]\n",
"test_end    = df_sorted['request_datetime'].iloc[-1]\n",
"\n",
"print(f'Train: {len(X_train):,} trips  ({train_start.date()} to {train_end.date()})')\n",
"print(f'Test:  {len(X_test):,} trips  ({test_start.date()} to {test_end.date()})')\n",
"print(f'\\nDate overlap: {\"YES -- PROBLEM!\" if train_end >= test_start else \"None -- correct!\"}')\n",
"print(f'\\nFeatures ({len(FEATURES)}): {FEATURES}')\n",
),

md(
"## 3.10  sklearn Pipeline and ColumnTransformer\n",
"\n",
"**Why Pipeline?**\n",
"\n",
"Without Pipeline, a common mistake is:\n",
"```python\n",
"# WRONG: fits on full dataset, leaks test distribution into training\n",
"X_scaled = scaler.fit_transform(X)  # <-- leakage here\n",
"X_train, X_test = train_test_split(X_scaled)\n",
"```\n",
"\n",
"With Pipeline:\n",
"```python\n",
"# CORRECT: fit only on train, transform both\n",
"pipe.fit(X_train, y_train)      # learns statistics from train only\n",
"X_test_transformed = pipe.transform(X_test)  # applies same stats to test\n",
"```\n",
"\n",
"Pipeline also makes deployment trivial: the entire preprocessing + model is one object\n",
"that you can serialize with `joblib.dump()` and load in the API.\n",
"\n",
"**ColumnTransformer** applies different transformations to different column subsets:\n",
"- Numeric columns (hour, day_of_week) -> StandardScaler\n",
"- Binary columns (is_weekend, is_rush_hour, etc.) -> passthrough (no transformation needed)\n",
"- Zone columns (PULocationID, DOLocationID) -> TargetEncoder\n",
"\n",
"StandardScaler is applied to numeric features so that the same preprocessor works\n",
"for both linear models (which require scaling) and tree models (which do not).\n",
),

code(
"# Cell 11: Build the preprocessing pipeline\n",
"\n",
"try:\n",
"    from category_encoders import TargetEncoder\n",
"except ImportError:\n",
"    raise ImportError('pip install category_encoders')\n",
"\n",
"numeric_features = ['pickup_hour', 'pickup_day_of_week']\n",
"binary_features  = ['is_weekend', 'is_rush_hour', 'is_night',\n",
"                    'operator', 'shared_request_flag', 'wav_request_flag']\n",
"zone_features    = ['PULocationID', 'DOLocationID']\n",
"\n",
"numeric_transformer = StandardScaler()\n",
"\n",
"# TargetEncoder: replaces each zone ID with its (smoothed) mean of the target.\n",
"# smoothing=10 means zones with < 10 trips get pulled toward the global mean,\n",
"# preventing overfitting on rare zones that appear only once in training data.\n",
"zone_transformer = TargetEncoder(smoothing=10)\n",
"\n",
"preprocessor = ColumnTransformer(transformers=[\n",
"    ('num',  numeric_transformer, numeric_features),\n",
"    ('bin',  'passthrough',       binary_features),\n",
"    ('zone', zone_transformer,    zone_features),\n",
"], remainder='drop')  # drop any column not explicitly listed\n",
"\n",
"print('Preprocessor built:')\n",
"print(f'  Numeric features    ({len(numeric_features)}): {numeric_features}')\n",
"print(f'  Binary features     ({len(binary_features)}): {binary_features}')\n",
"print(f'  Zone features       ({len(zone_features)}):  {zone_features}')\n",
"print(f'  Total input features: {len(FEATURES)}')\n",
"print(f'  Total output features: {len(numeric_features) + len(binary_features) + len(zone_features)}')\n",
),

code(
"# Cell 12: Fit on train, transform train and test, save artifacts\n",
"\n",
"# Fit ONLY on training data -- this is where the TargetEncoder learns\n",
"# zone -> mean ETA mappings, and StandardScaler learns mean and std.\n",
"# The test set statistics are never used during fitting.\n",
"X_train_proc = preprocessor.fit_transform(X_train, y_train)\n",
"X_test_proc  = preprocessor.transform(X_test)  # no y_test here -- never fit on test\n",
"\n",
"print(f'X_train before preprocessing: {X_train.shape}')\n",
"print(f'X_train after  preprocessing: {X_train_proc.shape}')\n",
"print(f'X_test  before preprocessing: {X_test.shape}')\n",
"print(f'X_test  after  preprocessing: {X_test_proc.shape}')\n",
"print()\n",
"\n",
"# Show sample of transformed values\n",
"import pandas as pd\n",
"feature_names = (numeric_features + binary_features + zone_features)\n",
"sample_df = pd.DataFrame(X_train_proc[:3], columns=feature_names)\n",
"print('Sample of transformed X_train (first 3 rows):')\n",
"display(sample_df.round(3))\n",
"\n",
"# Save processed arrays\n",
"np.save(PROCESSED_DIR / 'X_train.npy', X_train_proc)\n",
"np.save(PROCESSED_DIR / 'X_test.npy',  X_test_proc)\n",
"np.save(PROCESSED_DIR / 'y_train.npy', y_train.values)\n",
"np.save(PROCESSED_DIR / 'y_test.npy',  y_test.values)\n",
"\n",
"# Save fitted preprocessor\n",
"preprocessor_path = MODELS_DIR / 'preprocessor.joblib'\n",
"joblib.dump(preprocessor, preprocessor_path)\n",
"\n",
"print(f'\\nSaved:')\n",
"print(f'  {PROCESSED_DIR}/X_train.npy  ({X_train_proc.shape})')\n",
"print(f'  {PROCESSED_DIR}/X_test.npy   ({X_test_proc.shape})')\n",
"print(f'  {PROCESSED_DIR}/y_train.npy  ({len(y_train)} values)')\n",
"print(f'  {PROCESSED_DIR}/y_test.npy   ({len(y_test)} values)')\n",
"print(f'  {preprocessor_path}')\n",
),

md(
"## 3.13  Notebook 03 Summary\n",
"\n",
"### What We Built\n",
"\n",
"| Feature | Type | Engineering |\n",
"|---|---|---|\n",
"| `pickup_hour` | Numeric | Extracted from `request_datetime.dt.hour`, StandardScaled |\n",
"| `pickup_day_of_week` | Numeric | Extracted from `request_datetime.dt.dayofweek`, StandardScaled |\n",
"| `is_weekend` | Binary | 1 if day_of_week >= 5, passthrough |\n",
"| `is_rush_hour` | Binary | 1 if hour in [7,8,9,17,18,19], passthrough |\n",
"| `is_night` | Binary | 1 if hour in [22,23,0,1,2,3,4], passthrough |\n",
"| `operator` | Binary | HV0003->0, HV0005->1, passthrough |\n",
"| `shared_request_flag` | Binary | Y->1, N->0, passthrough |\n",
"| `wav_request_flag` | Binary | Y->1, N->0, passthrough |\n",
"| `PULocationID` | High-cardinality | TargetEncoder (smoothing=10) |\n",
"| `DOLocationID` | High-cardinality | TargetEncoder (smoothing=10) |\n",
"\n",
"### What We Saved\n",
"- `data/processed/X_train.npy`, `X_test.npy`, `y_train.npy`, `y_test.npy`\n",
"- `saved_models/preprocessor.joblib`\n",
"\n",
"### Leaky Columns Excluded\n",
"`trip_miles`, `trip_time`, `base_passenger_fare`, `driver_pay`, `tips`, `tolls`,\n",
"`pickup_datetime`, `dropoff_datetime`, `on_scene_datetime`\n",
"\n",
"---\n",
"\n",
"## Key Interview Questions -- Notebook 03\n",
"\n",
"**Q: What is data leakage and how did you prevent it?**  \n",
"A: Leakage is using information unavailable at prediction time as a feature.\n",
"Prevented by: (1) manually auditing all columns for post-trip data, (2) using\n",
"sklearn Pipeline which enforces fit-only-on-train for all transformations.\n",
"\n",
"**Q: Why log-transform the target?**  \n",
"A: `eta_seconds` is right-skewed. Training on the raw target means rare long ETAs\n",
"dominate MSE loss, causing the model to underfit short ETAs. Log-transform creates\n",
"a balanced, near-normal distribution. Inverse: `np.expm1(prediction)` gives seconds.\n",
"\n",
"**Q: Why chronological split instead of random?**  \n",
"A: Taxi data is time-ordered. Random split causes temporal leakage -- training on\n",
"January 25th trips to predict January 5th trips. Chronological split simulates\n",
"production: always train on past, predict on future.\n",
"\n",
"**Q: Why TargetEncoder for zones instead of OneHotEncoder?**  \n",
"A: 265 unique zones -> 265 sparse binary columns with OneHot. TargetEncoder creates\n",
"a single numeric column per zone (its smoothed mean ETA). No dimensionality explosion,\n",
"no multicollinearity, directly informative.\n",
"\n",
"**Q: What does the sklearn Pipeline do that prevents leakage?**  \n",
"A: Pipeline.fit() learns all transformer statistics from training data only.\n",
"Pipeline.transform() applies those learned statistics to any dataset -- including\n",
"test data that was never seen during fitting. Impossible to accidentally leak test data.\n",
"\n",
"**Q: What is smoothing in TargetEncoder?**  \n",
"A: Zones with very few trips get an unreliable zone-specific mean (e.g., one trip\n",
"that happened to be 600s). Smoothing=10 blends the zone mean with the global mean,\n",
"weighted by how many trips the zone has. Rare zones get pulled toward the global mean,\n",
"preventing overfitting on low-frequency zones.\n",
"\n",
"**Q: Why apply StandardScaler to numeric features if XGBoost doesn't need it?**  \n",
"A: We apply a single preprocessor that works for ALL models in Notebook 04 --\n",
"including Linear Regression and Ridge, which require scaled features. Applying the\n",
"same preprocessor to all models ensures a fair comparison on equal footing.\n",
),

]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.10.0"}
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

NB_PATH.write_text(json.dumps(nb, indent=1, ensure_ascii=True), encoding="utf-8")
n_md   = sum(1 for c in cells if c["cell_type"] == "markdown")
n_code = sum(1 for c in cells if c["cell_type"] == "code")
print(f"Notebook 03 written: {len(cells)} cells ({n_md} markdown, {n_code} code)")
print(f"Path: {NB_PATH}")
